//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("IcsIE", Namespace="", IsNullable=false)]
public partial class IcsIEType {
    
    /// <remarks/>
    public string MesTypMES20;
    
    /// <remarks/>
    public HEAHEAType HEAHEA;
    
    /// <remarks/>
    public TRACONCO1Type TRACONCO1;
    
    /// <remarks/>
    public TRACONCE1Type TRACONCE1;
    
    /// <remarks/>
    public TRAREPType TRAREP;
    
    /// <remarks/>
    public NOTPAR670Type NOTPAR670;
    
    /// <remarks/>
    public IcsIETypeGDSLOC GDSLOC;
    
    /// <remarks/>
    public IcsIETypeWAR WAR;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GOOITEGDS")]
    public GOOITEGDSType[] GOOITEGDS;
    
    /// <remarks/>
    public STAType STA;
    
    /// <remarks/>
    public MVDType MVD;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HEAHEAType {

    /// <remarks/>
    /// Код таможни ввоза
    public string RefNumEPT1;
    
    /// <remarks/>
    public string CusOffENT730;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string VerNumHEA992;
    
    /// <remarks/>
    public string RefNumHEA4;
    
    /// <remarks/>
    public string DocNumHEA5;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string PosCleVerHEA1005;
    
    /// <remarks/>
    public System.DateTime DecWorDatHEA999;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DecWorDatHEA999Specified;
    
    /// <remarks/>
    public string DecWorDatChReaTyp;
    
    /// <remarks/>
    public string DecWorDatChRea;
    
    /// <remarks/>
    public string DecPlaHEA394;
    
    /// <remarks/>
    public System.DateTime DecDatHEA383;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DecDatHEA383Specified;
    
    /// <remarks/>
    public string SurPC19;
    
    /// <remarks/>
    public System.DateTime DecAccDatHEA1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DecAccDatHEA1Specified;
    
    /// <remarks/>
    public System.DateTime IssDatHEA186;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IssDatHEA186Specified;
    
    /// <remarks/>
    public System.DateTime DatOfCanReqHEA147;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DatOfCanReqHEA147Specified;
    
    /// <remarks/>
    public System.DateTime ExtStoDatEXR68;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExtStoDatEXR68Specified;
    
    /// <remarks/>
    public string TypOfOpeHEA994;
    
    /// <remarks/>
    public string OpeCodHEA995;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TotNumOfIteHEA305;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TotNumOfPacHEA306;
    
    /// <remarks/>
    public decimal TotGroMasHEA307;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotGroMasHEA307Specified;
    
    /// <remarks/>
    public decimal TotNetMasHEA307;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotNetMasHEA307Specified;
    
    /// <remarks/>
    public string CouOfDesCodHEA30;
    
    /// <remarks/>
    public string CouOfDisCodHEA55;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TypOfPriGHEA1003;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 TesIndMES18;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TesIndMES18Specified;
    
    /// <remarks/>
    public string IdeOfMeaOfTraAtDHEA78;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 ConIndHEA96;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ConIndHEA96Specified;
    
    /// <remarks/>
    public string DelReqCodHEA992;
    
    /// <remarks/>
    public string DesOfDelReqHEA993;
    
    /// <remarks/>
    public string NatOfMeaOfTraCroHEA87;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TraModAtBorHEA76;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string InlTraModHEA75;
    
    /// <remarks/>
    public decimal ValDat12;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValDat12Specified;
    
    /// <remarks/>
    public string TypOfDeaHEA995;
    
    /// <remarks/>
    public string AddNot;
    
    /// <remarks/>
    public string Cur126;
    
    /// <remarks/>
    public decimal RatVal127;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RatVal127Specified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 RatVal127ManFlag;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RatVal127ManFlagSpecified;
    
    /// <remarks/>
    public decimal TotValHEA994;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotValHEA994Specified;
    
    /// <remarks/>
    public decimal TotValHEANat994;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotValHEANat994Specified;
    
    /// <remarks/>
    public decimal ExpInvAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExpInvAmSpecified;
    
    /// <remarks/>
    public decimal ExpInvNatAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExpInvNatAmSpecified;
    
    /// <remarks/>
    public decimal SubStrInvAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubStrInvAmSpecified;
    
    /// <remarks/>
    public decimal SubStrInvNatAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubStrInvNatAmSpecified;
    
    /// <remarks/>
    public decimal StaVal168;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StaVal168Specified;
    
    /// <remarks/>
    public decimal StaValNat168;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StaValNat168Specified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 CurDocIndHEA986;
    
    /// <remarks/>
    public string StaHEA379;
    
    /// <remarks/>
    public System.DateTime DatOfStaChaHEA987;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DatOfStaChaHEA987Specified;
    
    /// <remarks/>
    public string DefPay48;
    
    /// <remarks/>
    public string DefPayVGA48;
    
    /// <remarks/>
    public string CanDecHEA93;
    
    /// <remarks/>
    public string CusProCodGDS379;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 DeclBCom;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DeclBComSpecified;
    
    /// <remarks/>
    public string DeclBFilRea;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 MVD_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MVD_FLAGSpecified;
    
    /// <remarks/>
    public decimal TotValINVSTAT;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotValINVSTATSpecified;
    
    /// <remarks/>
    public HEAHEATypeTrdSta TrdSta;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TrdStaSpecified;
}

/// <remarks/>
/// признак актуальности документв
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum HEAHEATypeTesIndMES18 {
    
    /// <remarks/>
    /// не актуален
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    /// актуален
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum HEAHEATypeTrdSta {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MVDCalcPosNameType {
    
    /// <remarks/>
    public string CalcPosName;
    
    /// <remarks/>
    public decimal Value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValueSpecified;
    
    /// <remarks/>
    public string Currency;
    
    /// <remarks/>
    public decimal CurrRate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CurrRateSpecified;
    
    /// <remarks/>
    public decimal ValueNatCur;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValueNatCurSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CSubtractCostsType {
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_19;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_20;
    
    /// <remarks/>
    public MVDCalcPosNameType idok_dkl_mvd_21;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_22;
    
    /// <remarks/>
    public decimal B23SubtractCostsTotal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B23SubtractCostsTotalSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MVDCalcType {
    
    /// <remarks/>
    public decimal Value;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValueSpecified;
    
    /// <remarks/>
    public string Currency;
    
    /// <remarks/>
    public decimal CurrRate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CurrRateSpecified;
    
    /// <remarks/>
    public decimal ValueNatCur;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ValueNatCurSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class BOverheadsType {
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_13a;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_13b;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_13c;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_14a;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_14b;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_14c;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_14d;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_15;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_16;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_17a;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_17b;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_17c;
    
    /// <remarks/>
    public string B17DeliveryCostsPlaces;
    
    /// <remarks/>
    public decimal B18bBaseTotal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B18bBaseTotalSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ACalcBaseType {
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_11a;
    
    /// <remarks/>
    public MVDCalcType idok_dkl_mvd_11b;
    
    /// <remarks/>
    public decimal B12aBaseTotal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B12aBaseTotalSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CustValueCalcType {
    
    /// <remarks/>
    public ACalcBaseType ACalcBase;
    
    /// <remarks/>
    public BOverheadsType BOverheads;
    
    /// <remarks/>
    public CSubtractCostsType CSubtractCosts;
    
    /// <remarks/>
    public decimal B24DeclaredTotal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B24DeclaredTotalSpecified;
    
    /// <remarks/>
    public string CustValueCalcNOTES;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PrevDecisionType {
    
    /// <remarks/>
    public string PrevDecisionDocRef;
    
    /// <remarks/>
    public System.DateTime PrevDecisionDocDate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrevDecisionDocDateSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AgreementType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InvoiceType {
    
    /// <remarks/>
    public string InvoiceDocRef;
    
    /// <remarks/>
    public System.DateTime InvoiceDocDate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvoiceDocDateSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MVDBuyValType {
    
    /// <remarks/>
    public string NamBuy;
    
    /// <remarks/>
    public string StrAndNumBuy;
    
    /// <remarks/>
    public string PosCodBuy;
    
    /// <remarks/>
    public string CitBuy;
    
    /// <remarks/>
    public string CouBuy;
    
    /// <remarks/>
    public string TINBuy;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MVDSellValType {
    
    /// <remarks/>
    public string NamSell;
    
    /// <remarks/>
    public string StrAndNumSell;
    
    /// <remarks/>
    public string PosCodSell;
    
    /// <remarks/>
    public string CitSell;
    
    /// <remarks/>
    public string CouSell;
    
    /// <remarks/>
    public string TINSell;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MVDType {
    
    /// <remarks/>
    public MVDSellValType Seller;
    
    /// <remarks/>
    public MVDBuyValType Buyer;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Invoice", IsNullable=false)]
    public InvoiceType[] Invoices;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Agreement", IsNullable=false)]
    public AgreementsTypeAgreement[] Agreements;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PrevDecision", IsNullable=false)]
    public PrevDecisionType[] PrevDecisions;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 B7A_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B7A_FLAGSpecified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 B7B_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B7B_FLAGSpecified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 B7C_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B7C_FLAGSpecified;
    
    /// <remarks/>
    public string B7_NOTES;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 B8A_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B8A_FLAGSpecified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 B8B_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B8B_FLAGSpecified;
    
    /// <remarks/>
    public string B8_NOTES;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 B9A_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B9A_FLAGSpecified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 B9B_FLAG;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool B9B_FLAGSpecified;
    
    /// <remarks/>
    public string B9_NOTES;
    
    /// <remarks/>
    public CustValueCalcType CustValueCalc;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class AgreementsTypeAgreement : AgreementType {
    
    /// <remarks/>
    public string AgreementDocRef;
    
    /// <remarks/>
    public System.DateTime AgreementDocDate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AgreementDocDateSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class STAType {
    
    /// <remarks/>
    public STAValType InvAmSTA;
    
    /// <remarks/>
    public STAValType InsAmSTA;
    
    /// <remarks/>
    public STAValType OutFreAmSTA;
    
    /// <remarks/>
    public STAValType InnFreAmSTA;
    
    /// <remarks/>
    public STAValType OthCstAmSTA;
    
    /// <remarks/>
    public STAValType DedAmSTA;
    
    /// <remarks/>
    public STAValType InlTAXAmSTA;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class STAValType {
    
    /// <remarks/>
    public string CurSTAElm;
    
    /// <remarks/>
    public decimal AmSTAElm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AmSTAElmSpecified;
    
    /// <remarks/>
    public string DivMetAmSTA;
    
    /// <remarks/>
    public decimal RatVal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RatValSpecified;
    
    /// <remarks/>
    public decimal AmSTAElmNat;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AmSTAElmNatSpecified;
    
    /// <remarks/>
    public decimal AmSTAElmInv;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AmSTAElmInvSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TAXAType {
    
    /// <remarks/>
    public string TypOfTaxTAXA1;
    
    /// <remarks/>
    public decimal BasOfTaxTAXA2;
    
    /// <remarks/>
    public decimal TaxRate;
    
    /// <remarks/>
    public decimal TaxAmoTAXA5;
    
    /// <remarks/>
    public string PayOrdTAXA6;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 TaxManCal;
    
    /// <remarks/>
    public string TaxManCalRea;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TaxState;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string PvnId;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SPEMENMT2Type {
    
    /// <remarks/>
    public string AddInfCodMT23;
    
    /// <remarks/>
    public string AddInfCodDescr;
    
    /// <remarks/>
    public string AddInfMT21;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UniOfMeaType {
    
    /// <remarks/>
    public decimal QuaOfGooGDS376;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QuaOfGooGDS376Specified;
    
    /// <remarks/>
    public string BasUniOfMea377;
    
    /// <remarks/>
    public string BasUniOfMea378;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PREADMREFAR2Type {
    
    /// <remarks/>
    public string PreDocTyp;
    
    /// <remarks/>
    public string TitAR212;
    
    /// <remarks/>
    public string PreDocRefAR26;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 AllGoodsFlag;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AllGoodsFlagSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PRODOCDC2Type {
    
    /// <remarks/>
    public string DocCoDC28;
    
    /// <remarks/>
    public string DocTyp;
    
    /// <remarks/>
    public string TitDC29;

    /// <remarks/>
    public System.DateTime DocRegDat;
    //public string DocRegDat;

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DocRegDatSpecified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 OriFlag;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OriFlagSpecified;
    
    /// <remarks/>
    public string ComOfInfDC25;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 OthItemFlag;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OthItemFlagSpecified;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 ItemFileAtt;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemFileAttSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CONNR2Type {
    
    /// <remarks/>
    public string ConNumNR21;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PACGS2Type {
    
    /// <remarks/>
    public string KinOfPacGS23;
    
    /// <remarks/>
    public string MarNumOfPacGS21;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumOfPacGS24;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string NumOfPieGS25;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 OthItemPackFlag;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OthItemPackFlagSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GOOITEGDSType {
    
    /// <remarks/>
    public string GooDesGDS23;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IteNumGDS7;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IteNumB32F1;
    
    /// <remarks/>
    public string ComCodTarCodGDS10;
    
    /// <remarks/>
    public string CouOfOriCodGDS63;
    
    /// <remarks/>
    public decimal GroMasGDS46;
    
    /// <remarks/>
    public decimal NetMasGDS48;
    
    /// <remarks/>
    public string TARGDS60;
    
    /// <remarks/>
    public decimal QuaOfGooGDS376;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QuaOfGooGDS376Specified;
    
    /// <remarks/>
    public string BasUniOfMea377;
    
    /// <remarks/>
    public string BasUniOfMea378;
    
    /// <remarks/>
    public string CusProCodGDS379;
    
    /// <remarks/>
    public string AddCusProCodGDS340;
    
    /// <remarks/>
    public string FirAddTARCodGDS61;
    
    /// <remarks/>
    public string SecAddTARCodGDS62;
    
    /// <remarks/>
    public string SecAddTARCodGDS63;
    
    /// <remarks/>
    public decimal TotValGoo994;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotValGoo994Specified;
    
    /// <remarks/>
    public decimal TotValGooNat994;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TotValGooNat994Specified;
    
    /// <remarks/>
    public decimal ExpInvGooAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExpInvGooAmSpecified;
    
    /// <remarks/>
    public decimal ExpInvGooNatAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ExpInvGooNatAmSpecified;
    
    /// <remarks/>
    public decimal SubStrInvGooAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubStrInvGooAmSpecified;
    
    /// <remarks/>
    public decimal SubStrInvGooNatAm;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubStrInvGooNatAmSpecified;
    
    /// <remarks/>
    public decimal StaValOfGoo168;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StaValOfGoo168Specified;
    
    /// <remarks/>
    public decimal StaValOfGooNat168;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StaValOfGooNat168Specified;
    
    /// <remarks/>
    public decimal UniPriNat;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UniPriNatSpecified;
    
    /// <remarks/>
    public string QuoB39;
    
    /// <remarks/>
    public decimal GooInvB42;
    
    /// <remarks/>
    public string AppRecMet;
    
    /// <remarks/>
    public string PreB36;
    
    /// <remarks/>
    public STAValType GooInvSTA;
    
    /// <remarks/>
    public STAValType InsGooAmSTA;
    
    /// <remarks/>
    public STAValType OutGooFreAmSTA;
    
    /// <remarks/>
    public STAValType InnGooFreAmSTA;
    
    /// <remarks/>
    public STAValType OthGooCstAmSTA;
    
    /// <remarks/>
    public STAValType DedGooAmSTA;
    
    /// <remarks/>
    public STAValType InlGooTAXAmSTA;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PACGS2")]
    public PACGS2Type[] PACGS2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CONNR2")]
    public CONNR2Type[] CONNR2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PRODOCDC2")]
    public PRODOCDC2Type[] PRODOCDC2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PREADMREFAR2")]
    public PREADMREFAR2Type[] PREADMREFAR2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UNIOFMEa")]
    public UniOfMeaType[] UNIOFMEa;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SPEMENMT2")]
    public SPEMENMT2Type[] SPEMENMT2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TAXTA")]
    public TAXAType[] TAXTA;
    
    /// <remarks/>
    public HEAHEATypeTesIndMES18 ItemTaxManCal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemTaxManCalSpecified;
    
    /// <remarks/>
    public string ItemTaxManCalRea;
    
    /// <remarks/>
    public System.DateTime CompensationDate;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CompensationDateSpecified;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class WARType {
    
    /// <remarks/>
    public string WarTypWARTyp;
    
    /// <remarks/>
    public string WarTypWARId;
    
    /// <remarks/>
    public string WarTypWARCou;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GDSLOCType {
    
    /// <remarks/>
    public string CitGdsLoc;
    
    /// <remarks/>
    public string StrGdsLoc;
    
    /// <remarks/>
    public string StrNumLoc;
    
    /// <remarks/>
    public string PosCodGdsLoc;
    
    /// <remarks/>
    public string CouCodGdsLoc;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class NOTPAR670Type {
    
    /// <remarks/>
    public string NamNOTPAR672;
    
    /// <remarks/>
    public string StrNumNOTPAR673;
    
    /// <remarks/>
    public string PosCodNOTPAR676;
    
    /// <remarks/>
    public string CitNOTPAR674;
    
    /// <remarks/>
    public string CouCodNOTPAR675;
    
    /// <remarks/>
    public string TINNOTPAR671;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TRAREPType {
    
    /// <remarks/>
    public string NamTRE1;
    
    /// <remarks/>
    public string StrAndNumTRE1;
    
    /// <remarks/>
    public string PosCodTRE1;
    
    /// <remarks/>
    public string CitTRE1;
    
    /// <remarks/>
    public string CouCodTRE1;
    
    /// <remarks/>
    public string TINTRE1;
    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TRACONCE1Type {
    
    /// <remarks/>
    public string NamCE17;
    
    /// <remarks/>
    public string StrAndNumCE122;
    
    /// <remarks/>
    public string PosCodCE123;
    
    /// <remarks/>
    public string CitCE124;
    
    /// <remarks/>
    public string CouCE125;
    
    /// <remarks/>
    public string TINCE159;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TRACONCO1Type {
    
    /// <remarks/>
    public string NamCO17;
    
    /// <remarks/>
    public string StrAndNumCO122;
    
    /// <remarks/>
    public string PosCodCO123;
    
    /// <remarks/>
    public string CitCO124;
    
    /// <remarks/>
    public string CouCO125;
    
    /// <remarks/>
    public string TINCO159;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IcsIETypeGDSLOC {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GDSLOCStr", typeof(GDSLOCType))]
    [System.Xml.Serialization.XmlElementAttribute("GDSLOCUnStr", typeof(string))]
    public object Item;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IcsIETypeWAR : WARType {
}
